using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ezviz.net.domain.deviceInfo;
public enum SwitchType
{
    ALARM_TONE = 1,
    STREAM_ADAPTIVE = 2,
    LIGHT = 3,
    INTELLIGENT_ANALYSIS = 4,
    LOG_UPLOAD = 5,
    DEFENCE_PLAN = 6,
    PRIVACY = 7,
    SOUND_LOCALIZATION = 8,
    CRUISE = 9,
    INFRARED_LIGHT = 10,
    WIFI = 11,
    WIFI_MARKETING = 12,
    WIFI_LIGHT = 13,
    PLUG = 14,
    SLEEP = 21,
    SOUND = 22,
    BABY_CARE = 23,
    LOGO = 24,
    MOBILE_TRACKING = 25,
    CHANNELOFFLINE = 26,
    ALL_DAY_VIDEO = 29,
    AUTO_SLEEP = 32,
    ROAMING_STATUS = 34,
    DEVICE_4G = 35,
    ALARM_REMIND_MODE = 37,
    OUTDOOR_RINGING_SOUND = 39,
    INTELLIGENT_PQ_SWITCH = 40,
    DOORBELL_TALK = 101,
    HUMAN_INTELLIGENT_DETECTION = 200,
    LIGHT_FLICKER = 301,
    ALARM_LIGHT = 303,
    ALARM_LIGHT_RELEVANCE = 305,
    DEVICE_HUMAN_RELATE_LIGHT = 41,
    TAMPER_ALARM = 306,
    DETECTION_TYPE = 451,
    OUTLET_RECOVER = 600,
    CHIME_INDICATOR_LIGHT = 611,
    TRACKING = 650,
    CRUISE_TRACKING = 651,
    PARTIAL_IMAGE_OPTIMIZE = 700,
    FEATURE_TRACKING = 701,
}

